blueprint:
  name: Temperature and Humidity Change Notifications & Actions
  description: >
    # ↕️ Temperature and Humidity Change Notifications & Actions

    **Version: 1.0**

    Monitors all temperature and humidity sensors and triggers an action when
    any of them changes (increases or decreases) by a significant amount within
    a configurable time period in minutes (amount changed and minutes are both
    configurable). This is useful for detecting sudden environmental changes,
    device malfunctions, when the temperature and/or humidity changes due to
    opened doors/windows, to act as a heat alarm, etc.

    You can also choose any temperature or humidity sensors that should be ignored
    by this automation.
  domain: automation

  input:
    monitor_temperature:
      name: Monitor temperature sensors
      default: true
      selector:
        boolean:

    monitor_humidity:
      name: Monitor humidity sensors
      default: true
      selector:
        boolean:

    lookback_minutes:
      name: Lookback (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes

    temp_threshold:
      name: Temperature threshold (°C)
      default: 2.0
      selector:
        number:
          min: 0.1
          max: 20
          step: 0.1
          unit_of_measurement: °C

    humidity_threshold:
      name: Humidity threshold (%)
      default: 10
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"

    ignore_entities:
      name: Ignore sensors
      default: []
      selector:
        entity:
          multiple: true

    notification_action:
      name: Notification Action
      description: Preconfigured notification to send when change is detected
      default: []
      selector:
        action: {}

    other_action:
      name: Optional additional action
      description: Optional extra Home Assistant action to perform
      default: []
      selector:
        action: {}

    notification_message:
      name: Notification Message
      description: Template for notification
      default: "⚠️ Significant changes detected:\n{{ changes | join('\n') }}"
      selector:
        text:

mode: queued
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/1"

action:
  - variables:
      now_ts: "{{ as_timestamp(now()) }}"
      changes: []
      previous_values: "{{ previous_values if previous_values is defined else {} }}"

  - repeat:
      for_each: >
        {{ states.sensor
          | selectattr('state','is_number')
          | rejectattr('entity_id','in', ignore_entities)
          | list }}
      sequence:
        - variables:
            entity: "{{ repeat.item.entity_id }}"
            name: "{{ repeat.item.name }}"
            current: "{{ repeat.item.state | float(0) }}"
            device_class: "{{ repeat.item.attributes.device_class | default('') }}"
            is_temp: "{{ monitor_temperature and (device_class=='temperature' or 'temperature' in entity) }}"
            is_hum: "{{ monitor_humidity and (device_class=='humidity' or 'humidity' in entity) }}"
            prev_val: "{{ previous_values[entity]['value'] if entity in previous_values else current }}"
            prev_time: "{{ previous_values[entity]['time'] if entity in previous_values else now_ts }}"
            minutes_since: "{{ (now_ts - prev_time)/60 }}"
            diff: "{{ current - prev_val }}"

        - condition: template
          value_template: >
            {{ (is_temp or is_hum)
               and minutes_since >= lookback_minutes
               and ((is_temp and diff|abs >= temp_threshold) or (is_hum and diff|abs >= humidity_threshold)) }}

        - variables:
            msg: "{{ name }} changed by {{ diff|round(1) }}{{ '°C' if is_temp else '%' }} in last {{ minutes_since|int }} minutes"
            changes: "{{ changes + [msg] }}"

        # Update previous values
        - variables:
            previous_values: "{{ previous_values | combine({entity: {'value': current, 'time': now_ts}}) }}"

  # Execute notification if changes detected
  - choose:
      - conditions: "{{ changes | count > 0 }}"
        sequence:
          - variables:
              message: "{{ notification_message }}"
          # Run the preconfigured notification action
          - repeat:
              for_each: !input notification_action
              sequence:
                - choose:
                    - conditions: "true"
                      sequence:
                        - service: "{{ repeat.item.service }}"
                          data: "{{ repeat.item.data | default({'message': message}) }}"
          # Run optional additional actions
          - repeat:
              for_each: !input other_action
              sequence:
                - choose:
                    - conditions: "true"
                      sequence:
                        - service: "{{ repeat.item.service }}"
                          data: "{{ repeat.item.data | default({}) }}"
