blueprint:
  name: Temperature and Humidity Change Actions
  description: >
    # ↕️ Temperature and Humidity Change Actions

    **Version: 1.0**

    Monitors all temperature and humidity sensors and triggers an action when
    any of them changes (increases or decreases) by a significant amount within
    a configurable time period in minutes (amount changed and minutes are both
    configurable). This is useful for detecting sudden environmental changes,
    device malfunctions, when the temperature and/or humidity changes due to
    opened doors/windows, to act as a heat alarm, etc.

    You can also choose any temperature or humidity sensors that should be ignored
    by this automation.
  domain: automation

  input:
    monitor_temperature:
      name: Monitor temperature sensors
      default: true
      selector:
        boolean:

    monitor_humidity:
      name: Monitor humidity sensors
      default: true
      selector:
        boolean:

    lookback_minutes:
      name: Comparison lookback (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes

    temp_threshold:
      name: Temperature change threshold (°C)
      default: 2.0
      selector:
        number:
          min: 0.1
          max: 20.0
          step: 0.1
          unit_of_measurement: °C

    humidity_threshold:
      name: Humidity change threshold (%)
      default: 10
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"

    ignore_entities:
      name: Ignore sensors
      description: Sensors to exclude from monitoring.
      default: []
      selector:
        entity:
          multiple: true

    actions:
      name: Actions
      description: Actions to perform when a change is reached within the minutes specified.
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

variables:
  monitor_temperature: !input monitor_temperature
  monitor_humidity: !input monitor_humidity
  lookback_minutes: !input lookback_minutes
  temp_threshold: !input temp_threshold
  humidity_threshold: !input humidity_threshold
  ignore_entities: !input ignore_entities

trigger:
  # Check every minute
  - platform: time_pattern
    minutes: "/1"

action:
  - variables:
      changes: []

  - repeat:
      for_each: >
        {% set sensors = states.sensor
          | selectattr('state','is_number')
          | rejectattr('entity_id','in', ignore_entities)
          | list %}
        {{ sensors }}
      sequence:
        - variables:
            entity: "{{ repeat.item.entity_id }}"
            name: "{{ repeat.item.name }}"
            current: "{{ repeat.item.state | float(0) }}"
            device_class: "{{ repeat.item.attributes.device_class | default('') }}"
            is_temp: >
              {{ monitor_temperature and (device_class == 'temperature' or 'temperature' in entity) }}
            is_hum: >
              {{ monitor_humidity and (device_class == 'humidity' or 'humidity' in entity) }}
        - condition: template
          value_template: "{{ (is_temp or is_hum) and repeat.item.state not in ['unknown','unavailable'] }}"

        - variables:
            past: >
              {% set history = state_attr(entity, 'history') %}
              {% set old_state = states(entity, now() - timedelta(minutes=lookback_minutes)) %}
              {{ old_state.state | float(0) if old_state else current }}
            diff: "{{ current - past }}"
        - choose:
            - conditions: >
                {{ (is_temp and (diff | abs >= temp_threshold))
                   or (is_hum and (diff | abs >= humidity_threshold)) }}
              sequence:
                - variables:
                    msg: >
                      {{ '⚠️ ' ~ name ~ ' changed by ' ~ diff|round(1) ~ ('°C' if is_temp else '%') ~ ' in last ' ~ lookback_minutes ~ ' minutes' }}
                - variables:
                    changes: "{{ changes + [msg] }}"

  - choose:
      - conditions: "{{ changes | count > 0 }}"
        sequence:
          - variables:
              message: >
                Significant temperature or humidity changes detected:
                {{ '\n'.join(changes) }}
          - choose: []
            default: !input actions
