blueprint:
  name: Temperature and Humidity Change Actions 2
  description: >
    # ↕️ Temperature and Humidity Change Actions

    **Version: 1.0**

    Monitors all temperature and humidity sensors and triggers an alert when any
    of them changes (increase or decrease) by a configurable amount within a
    configurable time period. This is useful for detecting sudden environmental
    changes, device malfunctions, open doors/windows, or to act as a heat alarm.

    Each sensor is tracked individually so cooldown applies per entity.

    Stores previous values automatically using helpers, so changes
    persist across restarts.

    You can also choose any temperature or humidity sensors that should be ignored
    by this automation.
  domain: automation

  input:
    monitor_temperature:
      name: Monitor temperature sensors
      default: true
      selector:
        boolean:

    monitor_humidity:
      name: Monitor humidity sensors
      default: true
      selector:
        boolean:

    lookback_minutes:
      name: Comparison lookback (minutes)
      description: >
        Compare the current value to this many minutes ago. Defines the time window for detecting significant changes.
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes

    temp_threshold:
      name: Temperature change threshold (°C)
      default: 2.0
      selector:
        number:
          min: 0.1
          max: 10.0
          step: 0.1
          unit_of_measurement: °C

    humidity_threshold:
      name: Humidity change threshold (%)
      default: 10
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"

    ignore_entities:
      name: Ignore sensors
      description: Sensors to exclude from monitoring.
      default: []
      selector:
        entity:
          multiple: true

    actions:
      name: Actions
      description: >
        What to do when a significant temperature or humidity change is detected.
        (e.g. send a notification, play sound, flash lights, run script, etc.)
      default: []
      selector:
        action:

mode: queued
max_exceeded: silent

variables:
  monitor_temperature: !input monitor_temperature
  monitor_humidity: !input monitor_humidity
  lookback_minutes: !input lookback_minutes
  temp_threshold: !input temp_threshold
  humidity_threshold: !input humidity_threshold
  ignore_entities: !input ignore_entities

trigger:
  # Run every minute to check for changes
  - platform: time_pattern
    minutes: "/1"

action:
  - variables:
      now_ts: "{{ as_timestamp(now()) }}"
      changes: []

  - repeat:
      for_each: >
        {{ states.sensor | list }}
      sequence:
        - variables:
            entity: "{{ repeat.item.entity_id }}"
            name: "{{ repeat.item.name }}"
            current: "{{ repeat.item.state | float(0) }}"
            device_class: "{{ repeat.item.attributes.device_class | default('') }}"
            is_temp: >
              {{ monitor_temperature and (device_class == 'temperature' or 'temperature' in entity) }}
            is_hum: >
              {{ monitor_humidity and (device_class == 'humidity' or 'humidity' in entity) }}
        - condition: template
          value_template: >
            {{ (is_temp or is_hum) and entity not in ignore_entities and repeat.item.state not in ['unknown', 'unavailable'] }}

        # Store previous reading using an input_number and input_datetime per entity
        - variables:
            num_helper: "input_number.prev_{{ entity|replace('.', '_') }}"
            time_helper: "input_datetime.prev_{{ entity|replace('.', '_') }}"

        # Create helpers if they don’t exist yet
        - choose:
            - conditions: "{{ num_helper not in states }}"
              sequence:
                - service: input_number.create
                  data:
                    name: "Previous {{ name }}"
                    min: -100
                    max: 200
                    step: 0.01
                    initial: "{{ current }}"
                    id: "{{ num_helper }}"
            - conditions: "{{ time_helper not in states }}"
              sequence:
                - service: input_datetime.create
                  data:
                    name: "Previous {{ name }} time"
                    has_date: true
                    has_time: true
                    id: "{{ time_helper }}"

        - variables:
            prev_val: "{{ states(num_helper) | float(0) }}"
            prev_time: "{{ as_timestamp(states(time_helper)) if states(time_helper) not in ['unknown', 'unavailable', None] else 0 }}"
            minutes_since: "{{ (now_ts - prev_time) / 60 if prev_time > 0 else lookback_minutes + 1 }}"
            diff: "{{ current - prev_val }}"
        - choose:
            - conditions: >
                {{ minutes_since >= lookback_minutes and
                   ((is_temp and (diff | abs >= temp_threshold))
                    or (is_hum and (diff | abs >= humidity_threshold))) }}
              sequence:
                - variables:
                    msg: >
                      {{ '⚠️ ' ~ name ~ ' changed by ' ~ diff|round(1) ~ ('°C' if is_temp else '%') ~ ' in ' ~ (minutes_since|int) ~ ' min' }}
                - variables:
                    changes: "{{ changes + [msg] }}"

        # Always update last known state
        - service: input_number.set_value
          data:
            entity_id: "{{ num_helper }}"
            value: "{{ current }}"
        - service: input_datetime.set_datetime
          data:
            entity_id: "{{ time_helper }}"
            timestamp: "{{ now_ts }}"

  - choose:
      - conditions: "{{ changes | count > 0 }}"
        sequence:
          - variables:
              message: >
                Significant temperature or humidity change detected:
                {{ '\n'.join(changes) }}
          - choose: []
            default: !input actions
